import type { NextPage } from "next";
import Head from "next/head";
import { PageElementTmp } from "../components/elements";
import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const page = trpc.element.getPage.useQuery({ route: "" });

  return (
    <>
      <Head>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto flex min-h-screen flex-col items-center justify-center p-4">
        {page && page.data ? (
          <PageElementTmp element={page.data} page={true} edit={false} />
        ) : page && page.isLoading ? (
          <p>Loading page..</p>
        ) : (
          <p>No Home Page Set</p>
        )}
      </main>
    </>
  );
};

export default Home;
