import type { NextPage } from "next";
import Head from "next/head";
import PageElement from "../components/elements/Page";
import { env } from "../env/client.mjs";
import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const route = env.NEXT_PUBLIC_HOME_PAGE_ROUTE;

  // route is something like PageName-50fe8538-37b8-4dea-a435-63a9ae35553e
  // therefore, get the uuid only
  const pageRoute =
    route && (route as string).slice((route as string).indexOf("-") + 1);

  const page = pageRoute && trpc.element.getPage.useQuery({ route: pageRoute });

  console.log(route, pageRoute, page && page.data, PageElement);

  return (
    <>
      <Head>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto flex min-h-screen flex-col items-center justify-center p-4">
        {route && page && page.data ? (
          <PageElement element={page.data} page={true} edit={false} />
        ) : route && page && page.isLoading ? (
          <p>Loading page..</p>
        ) : (
          <p>No Home Page Set</p>
        )}
      </main>
    </>
  );
};

export default Home;
