import { AttributeType } from "@prisma/client";
import Head from "next/head";
import { useRouter } from "next/router";
import NavBar from "../../components/nav";
import { trpc } from "../../utils/trpc";

const ElementsPanel = () => {
  const router = useRouter();
  const createElement = trpc.element.create.useMutation();

  const handleCreateNewPage = async () => {
    const atts = [
      {
        name: "Title",
        type: AttributeType.Text,
        value: "",
      },
      {
        name: "Cover",
        type: AttributeType.Image,
        value: "",
      },
      {
        name: "Icon",
        type: AttributeType.Image,
        value: "",
      },
    ];

    const res = await createElement.mutateAsync({
      type: "Page",
      index: 0,
      atts,
    });

    if (res) {
      router.push(`/${res.route}`);
    }
  };

  return (
    <>
      <Head>
        <title>Elements</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="relative min-h-screen w-full">
        <div className="z-0 w-full bg-white bg-opacity-90">
          <div className="mx-auto flex max-w-4xl flex-col py-4 px-8 md:px-12 lg:px-24">
            {/* Content */}
            <p className="text-3xl font-bold">Elements</p>
            <p className="text-lg text-gray-500">Manage elements</p>
            <button
              onClick={handleCreateNewPage}
              className="mt-4 rounded-lg bg-secondary px-4 py-2 text-white hover:cursor-pointer hover:bg-secondary-focus"
            >
              Create New Empty Page
            </button>
          </div>
        </div>
        <NavBar />
      </main>
    </>
  );
};

export default ElementsPanel;
