import Head from "next/head";
import Link from "next/link";
import NavBar from "../../components/nav";

const AdminPanel = () => {
  return (
    <>
      <Head>
        <title>Admin</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="relative min-h-screen w-full">
        <div className="z-0 w-full bg-white bg-opacity-90">
          <div className="mx-auto flex max-w-4xl flex-col py-4 px-8 md:px-12 lg:px-24">
            {/* Content */}
            <p className="text-3xl font-bold">Admin</p>
            <p className="text-lg text-gray-500">
              Manage platform administration
            </p>
            <div className="mt-4 flex flex-row flex-wrap space-x-2">
              <Link href="/admin/groups">
                <div className="flex cursor-pointer flex-col items-center justify-center space-y-1 rounded-lg bg-gray-100 px-4 py-2 hover:bg-gray-200">
                  <p className="text-lg font-bold">Groups</p>
                  <p className="text-sm text-gray-500">Manage groups</p>
                </div>
              </Link>
              <Link href="/admin/users">
                <div className="flex cursor-pointer flex-col items-center justify-center space-y-1 rounded-lg bg-gray-100 px-4 py-2 hover:bg-gray-200">
                  <p className="text-lg font-bold">Users</p>
                  <p className="text-sm text-gray-500">Manage users</p>
                </div>
              </Link>
              <Link href="/admin/membership">
                <div className="flex cursor-pointer flex-col items-center justify-center space-y-1 rounded-lg bg-gray-100 px-4 py-2 hover:bg-gray-200">
                  <p className="text-lg font-bold">Membership</p>
                  <p className="text-sm text-gray-500">Manage membership</p>
                </div>
              </Link>
            </div>
          </div>
        </div>
        <NavBar />
      </main>
    </>
  );
};

export default AdminPanel;
