import Head from "next/head";
import NavBar from "../../components/nav";

const UsersPanel = () => {
  return (
    <>
      <Head>
        <title>Users</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="relative min-h-screen w-full">
        <div className="z-0 w-full bg-white bg-opacity-90">
          <div className="mx-auto flex max-w-4xl flex-col py-4 px-8 md:px-12 lg:px-24">
            {/* Content */}
            <p className="text-3xl font-bold">Users</p>
            <p className="text-lg text-gray-500">Manage platform{"'"}s users</p>
          </div>
        </div>
        <NavBar />
      </main>
    </>
  );
};

export default UsersPanel;
